name: GitHubActions Job Schedule

on: 
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Log Message
        run: echo "This is a test log message"

