name: GitHubActions Job Schedule

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Log Message
        run: echo "This is a test log message"

